
export const SYSTEMSWITCHMENU = 'SYSTEMSWITCHMENU'
export const LOGINSWITCH = 'LOGINSWITCH'
export const NODEVUE = 'NODEVUE'
export const USERLOGINDATA = 'USERLOGINDATA'
export const SETLOCALSTORAGE = 'SETLOCALSTORAGE'
export const GETLOCALSTORAGE = 'GETLOCALSTORAGE'
export const SETSTATE = 'SETSTATE'
export const GETLOGINDATA = 'GETLOGINDATA'
export const ADDTABLESTATE = 'ADDTABLESTATE'
//
export const SETTABLEEDIT = 'SETTABLEEDIT'





